In [1]:
import numpy as np
from progress.bar import Bar

In [8]:
kSkip = 4
l = kSkip / 2
dls = np.array([[1, 1], [l+1, 1], [1, l+1], [l+1, l+1]])
nDls = np.size(dls,1)
print(dls)
print('-')
print(nDls)

[[1. 1.]
 [3. 1.]
 [1. 3.]
 [3. 3.]]
-
2


In [35]:
for l in range(0, nDls):    
    dl = dls[l,:]
    print(dl)

[1. 1.]
[3. 1.]


In [5]:
np.arange(0, 195, 15)

array([  0,  15,  30,  45,  60,  75,  90, 105, 120, 135, 150, 165, 180])

In [8]:
A = [[1, 4, 5], 
    [-5, 8, 9]]
A

[[1, 4, 5], [-5, 8, 9]]

In [4]:
z = np.array(
    [[0, 0, 0, 0, 0],
     [1, 1, 1, 1, 1],
     [2, 2, 2, 2, 2],
     [3, 3, 3, 3, 3],
     [4, 4, 4, 4, 4],
     [5, 5, 5, 5, 5]]
)
n, m = np.shape(z)
xForw = np.array([1, 2, 3, 4, 5, 5])
xBack = [0, 0, 1, 2, 3, 4]
yForw = [1, 2, 3, 4, 4]
yBack = [0, 0, 1, 2, 3]

print('z[xForw]', z[xForw])
print('z[xForw][yForw]', z[xForw][yForw])
print('z[:][yForw]', z[:][yForw])
print('z[xBack][yForw]', z[xBack][yForw])
print('z[xBack]', z[xBack])
print('z[xBack][yBack]', z[xBack][yBack])
print('z[:][yBack]', z[:][yBack])
print('z[xForw][yBack]', z[xForw][yBack])
print('z[xForw]', z[xForw])


z[xForw] [[1 1 1 1 1]
 [2 2 2 2 2]
 [3 3 3 3 3]
 [4 4 4 4 4]
 [5 5 5 5 5]
 [5 5 5 5 5]]
z[xForw][yForw] [[2 2 2 2 2]
 [3 3 3 3 3]
 [4 4 4 4 4]
 [5 5 5 5 5]
 [5 5 5 5 5]]
z[:][yForw] [[1 1 1 1 1]
 [2 2 2 2 2]
 [3 3 3 3 3]
 [4 4 4 4 4]
 [4 4 4 4 4]]
z[xBack][yForw] [[0 0 0 0 0]
 [1 1 1 1 1]
 [2 2 2 2 2]
 [3 3 3 3 3]
 [3 3 3 3 3]]
z[xBack] [[0 0 0 0 0]
 [0 0 0 0 0]
 [1 1 1 1 1]
 [2 2 2 2 2]
 [3 3 3 3 3]
 [4 4 4 4 4]]
z[xBack][yBack] [[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [1 1 1 1 1]
 [2 2 2 2 2]]
z[:][yBack] [[0 0 0 0 0]
 [0 0 0 0 0]
 [1 1 1 1 1]
 [2 2 2 2 2]
 [3 3 3 3 3]]
z[xForw][yBack] [[1 1 1 1 1]
 [1 1 1 1 1]
 [2 2 2 2 2]
 [3 3 3 3 3]
 [4 4 4 4 4]]
z[xForw] [[1 1 1 1 1]
 [2 2 2 2 2]
 [3 3 3 3 3]
 [4 4 4 4 4]
 [5 5 5 5 5]
 [5 5 5 5 5]]


In [20]:
z = np.random.randint(1, 10, size=(10, 10))

In [30]:
kSkip = 2
a = np.arange(0, 10, kSkip)
b = np.arange(0, 10, kSkip)
z[a, b]

array([8, 2, 3, 3, 2])

In [50]:
a = [1]
print(np.concatenate((range(1,5),a), axis=0))
print(np.concatenate((a, range(1,5)), axis=0))

[1 2 3 4 1]
[1 1 2 3 4]


In [59]:
np.arange(0, 5, 2)

array([0, 2, 4])

In [61]:
z = np.array(
    [[0, 0, 0, 0, 0, 0, 0, 0, 0],
     [1, 1, 1, 1, 1, 1, 1, 1, 1],
     [2, 2, 2, 2, 2, 2, 2, 2, 2],
     [3, 3, 3, 3, 3, 3, 3, 3, 3],
     [4, 4, 4, 4, 4, 4, 4, 4, 4],
     [5, 5, 5, 5, 5, 5, 5, 5, 5],
     [6, 6, 6, 6, 6, 6, 6, 6, 6],
     [7, 7, 7, 7, 7, 7, 7, 7, 7],
     [8, 8, 8, 8, 8, 8, 8, 8, 8],
     [9, 9, 9, 9, 9, 9, 9, 9, 9],]
)

In [71]:
kSkip = 3
indsLx = np.arange(0, 9, kSkip)
indsLy = np.arange(0, 9, kSkip)
print(indsLx, indsLy)
zout = z[indsLx][:, indsLy]
zout

[0 3 6] [0 3 6]


array([[0, 0, 0],
       [3, 3, 3],
       [6, 6, 6]])

In [6]:
a = np.array([[1, 2], [3, 4]])
np.reshape(a, (4, 1)).flatten()

array([1, 2, 3, 4])

In [2]:
np.arange(0.0, 180.0, 15.0)

array([  0.,  15.,  30.,  45.,  60.,  75.,  90., 105., 120., 135., 150.,
       165.])

In [20]:
 x = [1, 2.5, 7, 10]
 y = [5.2, 7.7, 9.6 ,13.2]
 np.trapz(y, x)
 #np.trapz(x, y)

82.80000000000001

In [79]:
a = np.array([1, 2, 3])
bins = 5
step = len(a) / (bins * len(a))

mina = np.min(a) + step
maxa = np.max(a)
print(step, mina, maxa)

np.histogram(np.arange(mina, maxa, step), bins)

0.2 1.2 3


(array([2, 2, 1, 2, 2]), array([1.2 , 1.52, 1.84, 2.16, 2.48, 2.8 ]))