In [1]:
import numpy as np
from progress.bar import Bar

In [8]:
kSkip = 4
l = kSkip / 2
dls = np.array([[1, 1], [l+1, 1], [1, l+1], [l+1, l+1]])
nDls = np.size(dls,1)
print(dls)
print('-')
print(nDls)

[[1. 1.]
 [3. 1.]
 [1. 3.]
 [3. 3.]]
-
2


In [35]:
for l in range(0, nDls):    
    dl = dls[l,:]
    print(dl)

[1. 1.]
[3. 1.]


In [5]:
np.arange(0, 195, 15)

array([  0,  15,  30,  45,  60,  75,  90, 105, 120, 135, 150, 165, 180])

In [8]:
A = [[1, 4, 5], 
    [-5, 8, 9]]
A

[[1, 4, 5], [-5, 8, 9]]

In [2]:
z = np.array(
    [[0, 0, 0, 0, 0],
     [1, 1, 1, 1, 1],
     [2, 2, 2, 2, 2],
     [3, 3, 3, 3, 3],
     [4, 4, 4, 4, 4],
     [5, 5, 5, 5, 5]]
)
n, m = np.shape(z)
xForw = np.array([1, 2, 3, 4, 5, 5])
xBack = [0, 0, 1, 2, 3, 4]
yForw = [1, 2, 3, 4, 4]
yBack = [0, 0, 1, 2, 3]

print('z[xForw]', z[xForw])
print('z[xForw][yForw]', z[xForw][yForw])
print('z[:][yForw]', z[:][yForw])
print('z[xBack][yForw]', z[xBack][yForw])
print('z[xBack]', z[xBack])
print('z[xBack][yBack]', z[xBack][yBack])
print('z[:][yBack]', z[:][yBack])
print('z[xForw][yBack]', z[xForw][yBack])
print('z[xForw]', z[xForw])


z[xForw] [[1 1 1 1 1]
 [2 2 2 2 2]
 [3 3 3 3 3]
 [4 4 4 4 4]
 [5 5 5 5 5]
 [5 5 5 5 5]]
z[xForw][yForw] [[2 2 2 2 2]
 [3 3 3 3 3]
 [4 4 4 4 4]
 [5 5 5 5 5]
 [5 5 5 5 5]]
z[:][yForw] [[1 1 1 1 1]
 [2 2 2 2 2]
 [3 3 3 3 3]
 [4 4 4 4 4]
 [4 4 4 4 4]]
z[xBack][yForw] [[0 0 0 0 0]
 [1 1 1 1 1]
 [2 2 2 2 2]
 [3 3 3 3 3]
 [3 3 3 3 3]]
z[xBack] [[0 0 0 0 0]
 [0 0 0 0 0]
 [1 1 1 1 1]
 [2 2 2 2 2]
 [3 3 3 3 3]
 [4 4 4 4 4]]
z[xBack][yBack] [[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [1 1 1 1 1]
 [2 2 2 2 2]]
z[:][yBack] [[0 0 0 0 0]
 [0 0 0 0 0]
 [1 1 1 1 1]
 [2 2 2 2 2]
 [3 3 3 3 3]]
z[xForw][yBack] [[1 1 1 1 1]
 [1 1 1 1 1]
 [2 2 2 2 2]
 [3 3 3 3 3]
 [4 4 4 4 4]]
z[xForw] [[1 1 1 1 1]
 [2 2 2 2 2]
 [3 3 3 3 3]
 [4 4 4 4 4]
 [5 5 5 5 5]
 [5 5 5 5 5]]
