In [ ]:
import numpy as np
from progress.bar import Bar

In [ ]:
kSkip = 4
l = kSkip / 2
dls = np.array([[1, 1], [l+1, 1], [1, l+1], [l+1, l+1]])
nDls = np.size(dls,1)
print(dls)
print('-')
print(nDls)

In [ ]:
for l in range(0, nDls):    
    dl = dls[l,:]
    print(dl)

In [ ]:
np.arange(0, 195, 15)

In [ ]:
A = [[1, 4, 5], 
    [-5, 8, 9]]
A

In [ ]:
z = np.array(
    [[0, 0, 0, 0, 0],
     [1, 1, 1, 1, 1],
     [2, 2, 2, 2, 2],
     [3, 3, 3, 3, 3],
     [4, 4, 4, 4, 4],
     [5, 5, 5, 5, 5]]
)
n, m = np.shape(z)
xForw = np.array([1, 2, 3, 4, 5, 5])
xBack = [0, 0, 1, 2, 3, 4]
yForw = [1, 2, 3, 4, 4]
yBack = [0, 0, 1, 2, 3]

print('z[xForw]', z[xForw])
print('z[xForw][yForw]', z[xForw][yForw])
print('z[:][yForw]', z[:][yForw])
print('z[xBack][yForw]', z[xBack][yForw])
print('z[xBack]', z[xBack])
print('z[xBack][yBack]', z[xBack][yBack])
print('z[:][yBack]', z[:][yBack])
print('z[xForw][yBack]', z[xForw][yBack])
print('z[xForw]', z[xForw])


In [ ]:
z = np.random.randint(1, 10, size=(10, 10))

In [ ]:
kSkip = 2
a = np.arange(0, 10, kSkip)
b = np.arange(0, 10, kSkip)
z[a, b]

In [ ]:
a = [1]
print(np.concatenate((range(1,5),a), axis=0))
print(np.concatenate((a, range(1,5)), axis=0))

In [ ]:
np.arange(0, 5, 2)

In [ ]:
z = np.array(
    [[0, 0, 0, 0, 0, 0, 0, 0, 0],
     [1, 1, 1, 1, 1, 1, 1, 1, 1],
     [2, 2, 2, 2, 2, 2, 2, 2, 2],
     [3, 3, 3, 3, 3, 3, 3, 3, 3],
     [4, 4, 4, 4, 4, 4, 4, 4, 4],
     [5, 5, 5, 5, 5, 5, 5, 5, 5],
     [6, 6, 6, 6, 6, 6, 6, 6, 6],
     [7, 7, 7, 7, 7, 7, 7, 7, 7],
     [8, 8, 8, 8, 8, 8, 8, 8, 8],
     [9, 9, 9, 9, 9, 9, 9, 9, 9],]
)

In [ ]:
kSkip = 3
indsLx = np.arange(0, 9, kSkip)
indsLy = np.arange(0, 9, kSkip)
print(indsLx, indsLy)
zout = z[indsLx][:, indsLy]
zout

In [ ]:
a = np.array([[1, 2], [3, 4]])
np.reshape(a, (4, 1)).flatten()

In [ ]:
np.arange(0.0, 180.0, 15.0)

In [ ]:
 x = [1, 2.5, 7, 10]
 y = [5.2, 7.7, 9.6 ,13.2]
 np.trapz(y, x)
 #np.trapz(x, y)

In [ ]:
a = np.array([1, 2, 3])
bins = 5

step = len(a) / (bins * len(a))
mina = np.min(a) + step
maxa = np.max(a)
print(step, mina, maxa)

print(np.histogram(a, bins))
print(np.arange(mina, maxa, step))

In [ ]:
def mat_hist(a, bins):
    step = len(a) / (bins * len(a))
    mina = np.min(a) + step
    maxa = np.max(a)

    [counts, _] = np.histogram(a, bins)
    edges = np.arange(mina, maxa, step)
    return counts, edges

In [ ]:
counts, edges = mat_hist(a, bins)
print(counts, edges)

In [ ]:
t = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
mat_hist(t, 5)
# 1.9000    3.7000    5.5000    7.3000    9.1000
print(t[:-1] + ((t[1:] - t[:-1])/2))

In [ ]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

N, X = np.histogram(a, bins = 5)
print(N, X)


In [ ]:
t = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
count, bins = np.histogram(t, bins=np.linspace(1, 10, 5, endpoint=False))

bins = bins + 0.9
print(count, bins)

In [ ]:
t = np.array([1, 2, 3, 4, 5])
count, bins = np.histogram(t, bins=np.linspace(1, 5, 5, endpoint=False))

bins = bins + 0.4
print(count, bins)

In [ ]:
t = np.array([1, 2, 3, 4, 5, 6, 7, 8])
bins = np.linspace(1, 8, 5, endpoint=False)
delta = (bins[1] - bins[0])/2
count, bins = np.histogram(t, bins=bins)

bins = bins + delta
print(count, bins)

In [ ]:
def mat_hist(x, nbins):
    bins = np.linspace(np.min(x), np.max(x), nbins, endpoint=False)
    delta = (bins[1] - bins[0])/2
    count, bins = np.histogram(x, bins=bins)

    bins = bins + delta
    return count, bins

In [ ]:
t = np.array([1, 2, 3, 4, 5, 6, 7, 8])
# count, bins = np.histogram(t, bins=np.linspace(1, 8, 6, endpoint=False))
# bins = bins + 0.5833
# print(count, bins)
mat_hist(t, 6)

In [ ]:
from skimage.filters.rank import entropy
from skimage.morphology import square

t = np.array([[1, 1, 1, 0, 0, 1, 0, 0, 1],
              [1, 1, 1, 1, 0, 1, 1, 0, 1],
              [0, 1, 0, 0, 1, 0, 1, 1, 1],
              [1, 1, 1, 0, 0, 1, 0, 0, 1],
              [1, 1, 1, 1, 0, 1, 1, 0, 1],
              [0, 1, 0, 0, 1, 0, 1, 1, 1],
              [1, 1, 1, 0, 0, 1, 0, 0, 1],
              [1, 1, 1, 1, 0, 1, 1, 0, 1],
              [0, 1, 0, 0, 1, 0, 1, 1, 1]])
actual = entropy(t, square(3))

expected = np.array([
    [0.9183,0.8608,0.8916,0.9680,0.9510,0.9301,0.9867,0.9946,0.9751],
    [0.9510,0.9183,0.9183,0.9751,0.9510,0.9183,0.9751,0.9751,0.9510],
    [0.9183,0.8608,0.8916,0.9680,0.9510,0.9301,0.9867,0.9946,0.9751],
    [0.9183,0.8608,0.8916,0.9680,0.9510,0.9301,0.9867,0.9946,0.9751],
    [0.9510,0.9183,0.9183,0.9751,0.9510,0.9183,0.9751,0.9751,0.9510],
    [0.9751,0.9599,0.9410,0.9813,0.9510,0.9055,0.9599,0.9410,0.9183],
    [0.9751,0.9599,0.9410,0.9813,0.9510,0.9055,0.9599,0.9410,0.9183],
    [0.9510,0.9183,0.9183,0.9751,0.9510,0.9183,0.9751,0.9751,0.9510],
    [0.9751,0.9599,0.9410,0.9813,0.9510,0.9055,0.9599,0.9410,0.9183]
])

print(np.array_equal(expected, actual))
print(actual)
print(expected)


In [ ]:
import numpy as np
import matplotlib.pyplot as plt
s = [1,1,1,1,2,2,2,3,3,4,5,5,5,6,7,7,7,7,7,7,7]

xmin = 1
xmax = 7
step = 1
y, x = np.histogram(s, bins=np.linspace(xmin, xmax, int((xmax-xmin)/step)))

nbins = y.size
print(x)

plt.bar(x[:-1], y) #, width=x[1]-x[0], color='red', alpha=0.5)
plt.hist(s, bins=nbins) #, alpha=0.5)
plt.grid(True)
plt.show()

In [ ]:
h1 = np.histogram(s, bins=np.linspace(xmin, xmax, int((xmax-xmin)/step)))
print(h1)
h_plt = plt.hist(s, bins=h1[1]) #,alpha=0.5)
print(h_plt)

# Example

In [ ]:
t = np.array([11, 15, 16, 11, 10, 19, 17, 12, 18 ,16])
count, bins = np.histogram(t, bins=6)

print(count)
print(bins)

In [ ]:
from matplotlib import pyplot as plt 
import numpy as np  

plt.hist(t, bins = bins) 
plt.title("histogram") 
plt.show()

# Try

In [ ]:
from matplotlib import pyplot as plt 
import numpy as np  

x = np.array([11, 15, 16, 11, 10, 19, 17, 12, 18 ,16])

h1 = np.histogram(x, bins=np.linspace(xmin, xmax, int((xmax-xmin)/step)))
print(h1)
#h_plt = plt.hist(s, bins=h1[1])
#print(h_plt)


In [ ]:
from matplotlib import pyplot as plt 
import numpy as np  

x = np.array([10, 11, 11, 12, 15, 16, 16, 17, 18, 19])

nbins = 6
bins = np.linspace(np.min(x), np.max(x), nbins, endpoint=False)
delta = (bins[1] - bins[0])/2
bins = bins + delta
print("bins", bins)

# Ei hyötyä, _=ei käyttöä, hbins=bins
# [3 0 3 2] [10.9 12.7 14.5 16.3 18.1]
_, hbins = np.histogram(x, bins=bins)
print(_, hbins)

# Ei toimi
#[0 1 1 1 3 3 3 4 4 5]
#count = np.digitize(x, bins)
#print(count)


h_plt = plt.hist(x, bins=bins)
# c 3     1     0     3     1     2
# b 7     2     1     3     1     7


In [519]:
def mat_hist2(x, nbins=10):
    bins = np.linspace(np.min(x), np.max(x), nbins, endpoint=False)    
    delta = (bins[1] - bins[0])/2
    bins = bins + delta
    count, _ = np.histogram(x, bins=nbins)
    return count, bins

In [521]:
from matplotlib import pyplot as plt 
import numpy as np  

nbins = 8
x = np.array([10, 11, 11, 12, 15, 16, 16, 17, 18, 19])
#x = np.array([1, 1, 2, 2, 2, 3, 4, 4, 4, 4, 5, 5, 5, 5, 5])
count, bins = mat_hist2(x, nbins)
print(count, bins)
# i   0           1           2       3           4       6
# c   3           1           0       3           1       2
# b 10.7500   12.2500   13.7500   15.2500   16.7500   18.2500

#h_plt = plt.hist(x, bins=bins)

check [10.    11.125 12.25  13.375 14.5   15.625 16.75  17.875 19.   ]
[3 1 0 0 1 2 1 2] [10.5625 11.6875 12.8125 13.9375 15.0625 16.1875 17.3125 18.4375]
