In [1]:
import numpy as np
from progress.bar import Bar

In [8]:
kSkip = 4
l = kSkip / 2
dls = np.array([[1, 1], [l+1, 1], [1, l+1], [l+1, l+1]])
nDls = np.size(dls,1)
print(dls)
print('-')
print(nDls)

[[1. 1.]
 [3. 1.]
 [1. 3.]
 [3. 3.]]
-
2


In [35]:
for l in range(0, nDls):    
    dl = dls[l,:]
    print(dl)

[1. 1.]
[3. 1.]


In [5]:
np.arange(0, 195, 15)

array([  0,  15,  30,  45,  60,  75,  90, 105, 120, 135, 150, 165, 180])

In [8]:
A = [[1, 4, 5], 
    [-5, 8, 9]]
A

[[1, 4, 5], [-5, 8, 9]]

In [4]:
z = np.array(
    [[0, 0, 0, 0, 0],
     [1, 1, 1, 1, 1],
     [2, 2, 2, 2, 2],
     [3, 3, 3, 3, 3],
     [4, 4, 4, 4, 4],
     [5, 5, 5, 5, 5]]
)
n, m = np.shape(z)
xForw = np.array([1, 2, 3, 4, 5, 5])
xBack = [0, 0, 1, 2, 3, 4]
yForw = [1, 2, 3, 4, 4]
yBack = [0, 0, 1, 2, 3]

print('z[xForw]', z[xForw])
print('z[xForw][yForw]', z[xForw][yForw])
print('z[:][yForw]', z[:][yForw])
print('z[xBack][yForw]', z[xBack][yForw])
print('z[xBack]', z[xBack])
print('z[xBack][yBack]', z[xBack][yBack])
print('z[:][yBack]', z[:][yBack])
print('z[xForw][yBack]', z[xForw][yBack])
print('z[xForw]', z[xForw])


z[xForw] [[1 1 1 1 1]
 [2 2 2 2 2]
 [3 3 3 3 3]
 [4 4 4 4 4]
 [5 5 5 5 5]
 [5 5 5 5 5]]
z[xForw][yForw] [[2 2 2 2 2]
 [3 3 3 3 3]
 [4 4 4 4 4]
 [5 5 5 5 5]
 [5 5 5 5 5]]
z[:][yForw] [[1 1 1 1 1]
 [2 2 2 2 2]
 [3 3 3 3 3]
 [4 4 4 4 4]
 [4 4 4 4 4]]
z[xBack][yForw] [[0 0 0 0 0]
 [1 1 1 1 1]
 [2 2 2 2 2]
 [3 3 3 3 3]
 [3 3 3 3 3]]
z[xBack] [[0 0 0 0 0]
 [0 0 0 0 0]
 [1 1 1 1 1]
 [2 2 2 2 2]
 [3 3 3 3 3]
 [4 4 4 4 4]]
z[xBack][yBack] [[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [1 1 1 1 1]
 [2 2 2 2 2]]
z[:][yBack] [[0 0 0 0 0]
 [0 0 0 0 0]
 [1 1 1 1 1]
 [2 2 2 2 2]
 [3 3 3 3 3]]
z[xForw][yBack] [[1 1 1 1 1]
 [1 1 1 1 1]
 [2 2 2 2 2]
 [3 3 3 3 3]
 [4 4 4 4 4]]
z[xForw] [[1 1 1 1 1]
 [2 2 2 2 2]
 [3 3 3 3 3]
 [4 4 4 4 4]
 [5 5 5 5 5]
 [5 5 5 5 5]]


In [20]:
z = np.random.randint(1, 10, size=(10, 10))

In [30]:
kSkip = 2
a = np.arange(0, 10, kSkip)
b = np.arange(0, 10, kSkip)
z[a, b]

array([8, 2, 3, 3, 2])

In [50]:
a = [1]
print(np.concatenate((range(1,5),a), axis=0))
print(np.concatenate((a, range(1,5)), axis=0))

[1 2 3 4 1]
[1 1 2 3 4]


In [59]:
np.arange(0, 5, 2)

array([0, 2, 4])

In [61]:
z = np.array(
    [[0, 0, 0, 0, 0, 0, 0, 0, 0],
     [1, 1, 1, 1, 1, 1, 1, 1, 1],
     [2, 2, 2, 2, 2, 2, 2, 2, 2],
     [3, 3, 3, 3, 3, 3, 3, 3, 3],
     [4, 4, 4, 4, 4, 4, 4, 4, 4],
     [5, 5, 5, 5, 5, 5, 5, 5, 5],
     [6, 6, 6, 6, 6, 6, 6, 6, 6],
     [7, 7, 7, 7, 7, 7, 7, 7, 7],
     [8, 8, 8, 8, 8, 8, 8, 8, 8],
     [9, 9, 9, 9, 9, 9, 9, 9, 9],]
)

In [71]:
kSkip = 3
indsLx = np.arange(0, 9, kSkip)
indsLy = np.arange(0, 9, kSkip)
print(indsLx, indsLy)
zout = z[indsLx][:, indsLy]
zout

[0 3 6] [0 3 6]


array([[0, 0, 0],
       [3, 3, 3],
       [6, 6, 6]])

In [6]:
a = np.array([[1, 2], [3, 4]])
np.reshape(a, (4, 1)).flatten()

array([1, 2, 3, 4])

In [2]:
np.arange(0.0, 180.0, 15.0)

array([  0.,  15.,  30.,  45.,  60.,  75.,  90., 105., 120., 135., 150.,
       165.])

In [20]:
 x = [1, 2.5, 7, 10]
 y = [5.2, 7.7, 9.6 ,13.2]
 np.trapz(y, x)
 #np.trapz(x, y)

82.80000000000001

In [90]:
a = np.array([1, 2, 3])
bins = 5

step = len(a) / (bins * len(a))
mina = np.min(a) + step
maxa = np.max(a)
print(step, mina, maxa)

print(np.histogram(a, bins))
print(np.arange(mina, maxa, step))

0.2 1.2 3
(array([1, 0, 1, 0, 1]), array([1. , 1.4, 1.8, 2.2, 2.6, 3. ]))
[1.2 1.4 1.6 1.8 2.  2.2 2.4 2.6 2.8]


In [147]:
def mat_hist(a, bins):
    step = len(a) / (bins * len(a))
    mina = np.min(a) + step
    maxa = np.max(a)

    [counts, _] = np.histogram(a, bins)
    edges = np.arange(mina, maxa, step)
    return counts, edges

In [148]:
counts, edges = mat_hist(a, bins)
print(counts, edges)

[2 2 2 2 2] [1.2 1.4 1.6 1.8 2.  2.2 2.4 2.6 2.8 3.  3.2 3.4 3.6 3.8 4.  4.2 4.4 4.6
 4.8 5.  5.2 5.4 5.6 5.8 6.  6.2 6.4 6.6 6.8 7.  7.2 7.4 7.6 7.8 8.  8.2
 8.4 8.6 8.8 9.  9.2 9.4 9.6 9.8]


In [118]:
t = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
mat_hist(t, 5)
# 1.9000    3.7000    5.5000    7.3000    9.1000
print(t[:-1] + ((t[1:] - t[:-1])/2))

[1.5 2.5 3.5 4.5 5.5 6.5 7.5 8.5 9.5]


In [145]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

N, X = np.histogram(a, bins = 5)
print(N, X)


[2 2 2 2 2] [ 1.   2.8  4.6  6.4  8.2 10. ]


In [84]:
t = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
count, bins = np.histogram(t, bins=np.linspace(1, 10, 5, endpoint=False))

bins = bins + 0.9
print(count, bins)

[2 2 2 2] [1.9 3.7 5.5 7.3 9.1]


In [86]:
t = np.array([1, 2, 3, 4, 5])
count, bins = np.histogram(t, bins=np.linspace(1, 5, 5, endpoint=False))

bins = bins + 0.4
print(count, bins)

[1 1 1 1] [1.4 2.2 3.  3.8 4.6]


In [91]:
t = np.array([1, 2, 3, 4, 5, 6, 7, 8])
bins = np.linspace(1, 8, 5, endpoint=False)
delta = (bins[1] - bins[0])/2
count, bins = np.histogram(t, bins=bins)

bins = bins + delta
print(count, bins)

[2 1 2 1] [1.7 3.1 4.5 5.9 7.3]


In [92]:
def mat_hist(x, nbins):
    bins = np.linspace(np.min(x), np.max(x), nbins, endpoint=False)
    delta = (bins[1] - bins[0])/2
    count, bins = np.histogram(x, bins=bins)

    bins = bins + delta
    return count, bins

In [93]:
t = np.array([1, 2, 3, 4, 5, 6, 7, 8])
# count, bins = np.histogram(t, bins=np.linspace(1, 8, 6, endpoint=False))
# bins = bins + 0.5833
# print(count, bins)
mat_hist(t, 6)

(array([2, 1, 1, 1, 1]),
 array([1.58333333, 2.75      , 3.91666667, 5.08333333, 6.25      ,
        7.41666667]))